<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends EntityRepository
{
    public function getCount()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function clearDaily()
    {
        $this->createQueryBuilder('a')
            ->update('AppBundle:Challenge', 'a')
            ->set('a.isDaily', 0)
            ->getQuery()
            ->execute();
    }
}
