<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorRepository extends EntityRepository
{
    public function searchOne($queryString)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.name LIKE :string')
            ->setParameter('string', "%". $queryString ."%")
            ->getQuery();

        return $qb->getSingleResult();
    }
}
