<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getCount()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function search($queryString)
    {
        $qb = $this->createQueryBuilder('a')
        ->where('a.name LIKE :string')
            ->setParameter('string', "%". $queryString ."%");

        return $qb->getQuery()->getResult();
    }

    public function findByCategory($category, $limit)
    {
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c');

        $query = $query->where('c.name = :c')
            ->setParameter('c', $category)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
