<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getCount()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function search($queryString)
    {
        dump($queryString);
        $qb = $this->createQueryBuilder('a')  //add select and array for JSON
        ->where('a.name LIKE :string')
            ->setParameter('string', "%". $queryString ."%");

        return $qb->getQuery()->getResult();
    }
}
