<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getCount()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getProfil($id)
    {
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->Leftjoin('a.positions', 'p')
            ->addSelect('p')
            ->Leftjoin('a.games', 'g')
            ->addSelect('g')
            ->Leftjoin('a.badges', 'b')
            ->addSelect('b')
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();

        return $query;
    }

    public function getGames($user)
    {
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->Leftjoin('a.games', 'g')
            ->addSelect('g')
            ->where('a.id = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();

        return $query;
    }
}
