parameters:
#    parameter_name: value

services:
  cache.service:
      class: AppBundle\Service\Cache\CacheService
      arguments: [@session]

  api.game:
      class: AppBundle\Service\Api\ApiGameService
      arguments: [@cache.service, @session]

  api.igdb:
      class: AppBundle\Service\Api\ApiIgdbService
      arguments: [@cache.service]

  api.steam:
      class: AppBundle\Service\Api\ApiSteamService

  create.game.service:
      class: AppBundle\Service\CreateGameService
      arguments: [%upload.dir%]

  front.service:
      class: AppBundle\Service\FrontService

  back.service:
      class: AppBundle\Service\BackService
      arguments: [@security.password_encoder, %upload.dir%]