parameters:
#    parameter_name: value

services:
  cache.service:
      class: AppBundle\Service\Cache\CacheService
      arguments: [@session]

  api.caller:
      class: AppBundle\Service\Api\ApiCaller
      arguments: [@cache.service, @session]

  api.giant:
      class: AppBundle\Service\Api\ApiGiantService
      arguments: [@cache.service, @session]
      parent: api.caller

  api.igdb:
      class: AppBundle\Service\Api\ApiIgdbService
      arguments: [@cache.service]

  api.steam:
      class: AppBundle\Service\Api\ApiSteamService
      parent: api.caller

  create.game.service:
      class: AppBundle\Service\CreateGameService
      arguments: [%upload.dir%, @doctrine.orm.entity_manager]

  front.service:
      class: AppBundle\Service\FrontService

  back.service:
      class: AppBundle\Service\BackService
      arguments: [@security.password_encoder, %upload.dir%]

  notification.service:
      class: AppBundle\Service\NotificationService
      arguments: [@snc_redis.default]

  notification.listener:
      class: AppBundle\Listener\NotificationListener
      arguments: [@notification.service, %notification.status%, @security.token_storage, @session]
      tags:
          - { name: kernel.event_listener, event: kernel.response, method: updateNotification }