# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  cache.service:
      class: AppBundle\Service\CacheService
      arguments: [%cache.dir%]

  api.game:
      class: AppBundle\Service\Api\ApiGameService
      arguments: [@cache.service]

  api.igdb:
      class: AppBundle\Service\Api\ApiIgdbService
      arguments: [@cache.service]

  steam.api:
      class: AppBundle\Service\Api\ApiSteamService

  load.game.service:
      class: AppBundle\Service\GameService

  front.service:
      class: AppBundle\Service\FrontService

  back.service:
      class: AppBundle\Service\BackService
      arguments: [@security.password_encoder, %upload.dir%]